package com.cordys.coe.birtconnector;

import com.eibus.localization.IStringResource;
import com.eibus.tools.internal.MessageBundle;
import com.eibus.tools.internal.MessageBundleGenerator;
import com.eibus.tools.internal.MessageText;

/**
 * This code is generated by running com.eibus.tools.internal.MessageGenerator.
 *
 * Generated by :senthil.kumar
 * Input file   :com.cordys.coe.birtconnector.Messages.xml
 * Generated at :Tue Dec 04 16:26:59 IST 2012
 */

@MessageBundle(value="com.cordys.coe.birtconnector.Messages", idConversion=true)
public class Messages
{ 

	private static int s_fieldIndexer = 0;
	private static IStringResource getMessage() { return MessageBundleGenerator.getMessage(Messages.class, s_fieldIndexer++); }

	@MessageText("Error while starting the service container")
	public static final IStringResource startError = getMessage();

	@MessageText("Request - ReportName : {0} ** OutputFormat : {1} ** Embeddable : {2} ** OutputToFile : {3} ** EncodeFile : {4} ** SAMLart: {5}")
	public static final IStringResource requestInfo = getMessage();

	@MessageText("Requested Method Name : {0}")
	public static final IStringResource requestedMethod = getMessage();
	
	@MessageText("Requested File {0} not found")
	public static final IStringResource requestedFileNotFound = getMessage();
	
	@MessageText("Unexpected Exception")
	public static final IStringResource unexpected = getMessage();

}